### PR TITLE
Add name in EIP712 domain

### PR DESCRIPTION
**Pull request by MerlinEgalite**
Fixes https://github.com/cantinasec/review-morpho-blue-1/issues/38

Why we did not include it:
https://github.com/morpho-org/morpho-blue/pull/425

To be discussed.

### CODE REVIEW

**Review by Rubilmax — APPROVED** [review]

**Review by Jean-Grimal — APPROVED** [review]

**Review by MathisGD — CHANGES_REQUESTED** [review]
I'm still against, I think that this is more dangerous than useful

**Comment by Rubilmax** [comment]
> I'm still against, I think that this is more dangerous than useful

How is it dangerous? The chain id and the verifying contract's address is hashed into the domain, so it's only a matter of UI?

**Comment by Rubilmax** [comment]
> https://github.com/morpho-org/morpho-blue/pull/425#issue-1863332811

Ah right, fair point!

**Comment by MerlinEgalite** [comment]
Stermi POV: https://github.com/cantinasec/review-morpho-blue-1/issues/38#issuecomment-1770483067

**Pull request closed without merging**
