### PR TITLE
feat(audit): fixing typo in security review report

### PR DESCRIPTION
**Pull request by tomrpl**
Updating the security review report

### CODE REVIEW

**Comment by MathisGD** [comment]
isn't it better to keep the same date?

**Review by MerlinEgalite — CHANGES_REQUESTED** [review]
Same question, why changing the date?

**Review by Rubilmax — APPROVED** [review]

**Comment by Rubilmax** [comment]
> @tomrpl yes original date (we don't really care about the date of the edit)

the date inside the doc has been updated

**Review by MerlinEgalite — APPROVED** [review]

**Comment by Rubilmax** [comment]
> ok but if we find an other typo in 6 month we don't want to update the date right. What we care about is the date of the audit

I agree, but then we need to warn OZ not to update the date of the report?

**Comment by tomrpl** [comment]
> then we need to warn OZ not to update the date of the report?
In my opinion this is the best way to proceed!

**Review by MathisGD — APPROVED** [review]

**Pull request merged**
