### PR TITLE
fix(authorization): revert already set error

### PR DESCRIPTION
**Pull request by Rubilmax**
- Fixes https://github.com/morpho-org/morpho-blue/pull/630#discussion_r1430371174

### CODE REVIEW

**Review by adhusson — APPROVED** [review]

**Review by QGarchery — APPROVED** [review]
Should also remove the corresponding test, but otherwise LGTM

**Review by MerlinEgalite — COMMENTED** [review]
we don't delete it for `setAuthorization`? I feel this is useless as well and a bit weird to have 2 different requirements for the same functionality

**Comment by Rubilmax** [comment]
> we don't delete it for `setAuthorization`? I feel this is useless as well and a bit weird to have 2 different requirements for the same functionality

This argument can also be used to defend the introduction of such requirement: why would we require not already set fee but not in setAuthorization* functions?

In the end, I am convinced we were inconsistent, though I am not convinced it is a big deal...

**Comment by MerlinEgalite** [comment]
But now we're being weirdly inconsistent it's even more disturbing to me

**Comment by Rubilmax** [comment]
> But now we're being weirdly inconsistent it's even more disturbing to me

Mb I wasn't clear: I was arguing we shouldn't revert the change at all!

**Comment by Rubilmax** [comment]
Another rationale behind this PR would be to simply revert the changes to the old way, even if it can be considered inconsistent, because it still works and there's no big deal

**Comment by QGarchery** [comment]
> why would we require not already set fee but not in setAuthorization* functions?

For `setAuthorizationWithSig` it's because the function is inherently more complicated becuase signatures are asynchronous by nature. I don't feel like just because it looks disturbing it means that it is incorrect.

You can also look at it another way: we are never in the "already set" case for `setAuthorizationWithSig` because it's at least changing the nonce. If we really want to return `ALREADY_SET`, we could change `INVALID_NONCE` into `ALREADY_SET`

**Review by MathisGD — APPROVED** [review]

**Review by MathisGD — APPROVED** [review]

**Review by Rubilmax — COMMENTED** [review]
LGTM

**Review by MerlinEgalite — COMMENTED** [review]
Let's add a comment no?

**Comment by Rubilmax** [comment]
> Let's add a comment no?

Something like:
`/// Do not check whether authorization is already set because the nonce increment is a desired side-effect.`

**Comment by MerlinEgalite** [comment]
> > Let's add a comment no?
> 
> Something like: `/// Do not check whether authorization is already set because the nonce increment is a desired side-effect.`

LGTM

**Review by MerlinEgalite — APPROVED** [review]

**Review by MathisGD — APPROVED** [review]

**Review by Jean-Grimal — APPROVED** [review]

**Review by QGarchery — APPROVED** [review]

**Pull request merged**
